### PR TITLE
One login saml setup

### PR DESCRIPTION
**Pull request by jesse-codefresh**
as I mentioned to you in private @kostis-codefresh, I wasn't able to change the list. So we are seeing them as bullets.

### CODE REVIEW

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/one-login-saml-setup/docs/

**Comment by jesse-codefresh** [comment]
@lukasgoodfellow 
can you check this, as you reported please?

**Comment by lukasgoodfellow** [comment]
@jesse-codefresh this looks good to me.  thank you

**Comment by jesse-codefresh** [comment]
.

**Pull request merged**
