### PR TITLE
Support Ticket Templates

### PR DESCRIPTION
**Pull request by mnmlluke**
PR to add Support Ticket Templates for customers to use when submitting tickets to support

### CODE REVIEW

**Comment by mnmlluke** [comment]
@paul-codefresh this is just the sample so far for end users to submit requests.

I know its not complete but wanted to get this started

Preview can be found [here](http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/add-support-ticket-template/docs/docs/kb/articles/support-ticket-examples/)

**Comment by NimRegev** [comment]
@paul-codefresh @taylor-gill I want to add this as a separate topic in the KB bucket as otherwise users will not be aware of this in the midst of all the How Tos. Let me know

**Comment by lrochette** [comment]
the title has a closing ouble quote but not an opening one

> Create support tickets for bugs, feature requests using our templates”

The format makes it hard to figure what to do
I would write it as a code sample (maybe with marked down for ZD)

**Comment by mnmlluke** [comment]
@lrochette I believe we do not use markdown for zendesk. I changed the template as Quoted Text to make it easier to read. If they copy and paste this should keep the format.

@NimRegev I moved outside of the KB Articles to its own level. This should not be easier to find.

**Review by lrochette — APPROVED** [review]
Looks better

**Pull request merged**
