### PR TITLE
[WORK IN PROGRESS -- do not merge] Docs restructuring

### PR DESCRIPTION
**Pull request by anna-codefresh**

### CODE REVIEW

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/doc-restructure/docs/

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/doc-restructure/docs/

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/doc-restructure/docs/

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/doc-restructure/docs/

**Comment by kostis-codefresh** [comment]
Now available at https://codefresh.io/csdp-docs/

**Pull request closed without merging**
