### PR TITLE
updated runner installation on GKE

### PR DESCRIPTION
**Pull request by mikhail-klimko**

### CODE REVIEW

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/runner-installation/docs/

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/runner-installation/docs/

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/runner-installation/docs/

**Review by jesse-codefresh — APPROVED** [review]
.

**Pull request merged**
