### PR TITLE
Add Rancher RKE section to Runner Installation doc

### PR DESCRIPTION
**Pull request by TedSpinks**
I wasn't able to preview the rendered markdown with all the images (5). Please take a look to make sure it looks OK.

### CODE REVIEW

**Comment by TedSpinks** [comment]
Hi @itai-codefresh, how do I get this change to show up in the staging environment?  Should I make the PR target a different branch or something?  Thanks for your help!

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/runner-rancher/docs/

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/runner-rancher/docs/

**Comment by TedSpinks** [comment]
Fixed all the formatting.  This PR is now ready for review!

**Pull request merged**
