### PR TITLE
updated GKE Runner installation

### PR DESCRIPTION
**Pull request by mikhail-klimko**

### CODE REVIEW

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/runner_gke_patch-1/docs/

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/runner_gke_patch-1/docs/

**Comment by lukasgoodfellow** [comment]
Fixed indentation from

Screen Shot 2021-09-24 at 08 15 38

to

Screen Shot 2021-09-24 at 08 26 08

make it easier to read on smaller screens.

**Review by lukasgoodfellow — APPROVED** [review]

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/runner_gke_patch-1/docs/

**Pull request merged**
