### PR TITLE
upd codefresh-runner.md

### PR DESCRIPTION
**Pull request by mikhail-klimko**

### CODE REVIEW

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/CR-5118/docs/

**Comment by mikhail-klimko** [comment]
http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/CR-5118/docs/docs/administration/codefresh-runner/#runner-architecture-overview

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/CR-5118/docs/

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/CR-5118/docs/

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/CR-5118/docs/

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/CR-5118/docs/

**Review by francisco-codefresh — APPROVED** [review]
LGreatTM!

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/CR-5118/docs/

**Pull request merged**
