### PR TITLE
edited as per Vadim

### PR DESCRIPTION
**Pull request by jesse-codefresh**

### CODE REVIEW

**Comment by jesse-codefresh** [comment]
please wait with Merge until I confirm with @vadim-kharin-codefresh

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/sso-documentation/docs/

**Comment by itai-codefresh** [comment]
[CI] Staging environment is at http://staging-docs.codefresh.io.s3-website.us-east-1.amazonaws.com/sso-documentation/docs/

**Comment by jesse-codefresh** [comment]
@vadim-kharin-codefresh please check.

**Review by vadim-kharin-codefresh — APPROVED** [review]

**Pull request merged**
